services:
  gamelistdb_dev:
    image: postgres:15
    container_name: gamelistdb_dev
    environment:
      POSTGRES_DB: gamelistdb_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      # volumes:
      # - gamelistdb_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

  # volumes:
  # gamelistdb_dev_data:
